### PR TITLE
WIP: Add type stubs

### PR DESCRIPTION
**Pull request by MartinThoma**
This is an example how type stubs can look like for alembic

### Description
See https://github.com/sqlalchemy/alembic/issues/745 for discussions

### Checklist
This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

### CODE REVIEW

**Comment by MartinThoma** [comment]
After this change, mypy still shows errors:

```
$ mypy .
alembic/util/messaging.pyi:13: error: Invalid type comment or annotation
alembic/ddl/mysql.pyi:43: error: Name 'MySQLModifyColumn' is not defined
setup.py:12: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
alembic/util/langhelpers.py:11: error: Module 'alembic.util.compat' has no attribute 'with_metaclass'
alembic/util/langhelpers.py:20: error: Unsupported dynamic base class "with_metaclass"
alembic/util/langhelpers.py:29: error: Need type annotation for '_setups'
alembic/util/langhelpers.py:238: error: Incompatible types in assignment (expression has type "Callable[[immutabledict, VarArg(Any), KwArg(Any)], Any]", base class "dict" defined the type as "Callable[[Dict[Any, Any], Any], None]")
alembic/util/langhelpers.py:238: error: Incompatible types in assignment (expression has type "Callable[[immutabledict, VarArg(Any), KwArg(Any)], Any]", base class "dict" defined the type as "Callable[[Dict[Any, Any], Any, Any], None]")
alembic/util/langhelpers.py:238: error: Incompatible types in assignment (expression has type "Callable[[immutabledict, VarArg(Any), KwArg(Any)], Any]", base class "object" defined the type as "Callable[[object, str, Any], None]")
alembic/util/langhelpers.py:238: error: Incompatible types in assignment (expression has type "Callable[[immutabledict, VarArg(Any), KwArg(Any)], Any]", base class "dict" defined the type as "Callable[[Dict[Any, Any]], None]")
alembic/util/langhelpers.py:238: error: Incompatible types in assignment (expression has type "Callable[[immutabledict, VarArg(Any), KwArg(Any)], Any]", base class "MutableMapping" defined the type as overloaded function)
alembic/util/langhelpers.py:238: error: Incompatible types in assignment (expression has type "Callable[[immutabledict, VarArg(Any), KwArg(Any)], Any]", base class "dict" defined the type as "Callable[[Dict[Any, Any]], Tuple[Any, Any]]")
alembic/util/langhelpers.py:238: error: Incompatible types in assignment (expression has type "Callable[[immutabledict, VarArg(Any), KwArg(Any)], Any]", base class "dict" defined the type as "Callable[[Dict[Any, Any], Any, Any], Any]")
alembic/util/langhelpers.py:240: error: Incompatible types in assignment (expression has type "Callable[[immutabledict, VarArg(Any), KwArg(Any)], Any]", base class "dict" defined the type as overloaded function)
alembic/util/__init__.py:14: error: Module 'alembic.util.messaging' has no attribute 'err'
alembic/util/__init__.py:17: error: Module 'alembic.util.messaging' has no attribute 'obfuscate_url_pw'
alembic/testing/assertions.py:17: error: Module 'alembic.util.compat' has no attribute 'py3k'
alembic/testing/assertions.py:62: error: Need type annotation for '_dialect_mods' (hint: "_dialect_mods: Dict[<type>, <type>] = ...")
alembic/ddl/impl.py:12: error: Module 'alembic.util.compat' has no attribute 'text_type'
alembic/ddl/impl.py:13: error: Module 'alembic.util.compat' has no attribute 'with_metaclass'
alembic/ddl/impl.py:24: error: Need type annotation for '_impls' (hint: "_impls: Dict[<type>, <type>] = ...")
alembic/ddl/impl.py:29: error: Unsupported dynamic base class "with_metaclass"
alembic/operations/ops.py:37: error: Need type annotation for '_mutations'
alembic/autogenerate/render.py:13: error: Module 'alembic.util.compat' has no attribute 'StringIO'
alembic/ddl/postgresql.py:41: error: Incompatible types in assignment (expression has type "Tuple[Set[str], Set[str]]", base class "DefaultImpl" defined the type as "Tuple[Set[str]]")
alembic/script/revision.py:925: error: Need type annotation for 'nextrev'
alembic/script/revision.py:928: error: Need type annotation for '_all_nextrev'
alembic/config.py:10: error: Module 'alembic.util.compat' has no attribute 'SafeConfigParser'
alembic/testing/fixtures.py:23: error: Module 'alembic.util.compat' has no attribute 'configparser'
alembic/testing/fixtures.py:25: error: Module 'alembic.util.compat' has no attribute 'text_type'
alembic/testing/fixtures.py:43: error: Need type annotation for '_engs' (hint: "_engs: Dict[<type>, <type>] = ...")
tests/test_script_consumption.py:170: error: Incompatible types in assignment (expression has type "str", base class "ApplyVersionsFunctionalTest" defined the type as "bool")
tests/test_script_consumption.py:176: error: Incompatible types in assignment (expression has type "str", base class "ApplyVersionsFunctionalTest" defined the type as "bool")
tests/test_script_consumption.py:184: error: Incompatible types in assignment (expression has type "str", base class "ApplyVersionsFunctionalTest" defined the type as "bool")
tests/test_script_consumption.py:690: error: Incompatible types in assignment (expression has type "str", base class "IgnoreFilesTest" defined the type as "bool")
tests/test_script_consumption.py:694: error: Incompatible types in assignment (expression has type "str", base class "IgnoreFilesTest" defined the type as "bool")
tests/test_script_consumption.py:700: error: Incompatible types in assignment (expression has type "str", base class "IgnoreFilesTest" defined the type as "bool")
tests/_autogen_fixtures.py:212: error: Need type annotation for 'configure_opts' (hint: "configure_opts: Dict[<type>, <type>] = ...")
alembic/testing/plugin/plugin_base.py:25: error: Name 'ABC' already defined on line 22
tests/test_autogen_indexes.py:1203: error: Definition of "__requires__" in base class "NoUqReflection" is incompatible with definition in base class "AutogenerateUniqueIndexTest"
tests/test_autogen_diffs.py:587: error: Incompatible types in assignment (expression has type "str", base class "ModelOne" defined the type as "None")
tests/test_autogen_diffs.py:731: error: Need type annotation for 'configure_opts' (hint: "configure_opts: Dict[<type>, <type>] = ...")
tests/test_autogen_diffs.py:1190: error: Incompatible types in assignment (expression has type "str", base class "AutogenVersionTableTest" defined the type as "None")
tests/test_autogen_diffs.py:1203: error: Incompatible types in assignment (expression has type "str", base class "AutogenVersionTableTest" defined the type as "None")
tests/test_autogen_diffs.py:1384: error: Incompatible types in assignment (expression has type "str", base class "ModelOne" defined the type as "None")
tests/test_autogen_composition.py:250: error: Incompatible types in assignment (expression has type "str", base class "ModelOne" defined the type as "None")
Found 46 errors in 19 files (checked 85 source files)
```

**Comment by MartinThoma** [comment]
Before this change, there were more:

```
$ mypy . --ignore-missing-imports                  
setup.py:12: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
alembic/util/compat.py:51: error: Name 'StringIO' already defined (possibly by an import)
alembic/util/compat.py:71: error: Name 'compat_builtins' already defined (by an import)
alembic/util/compat.py:73: error: Name 'basestring' is not defined
alembic/util/compat.py:74: error: Cannot assign multiple types to name "binary_type" without an explicit "Type[...]" annotation
alembic/util/compat.py:74: error: Incompatible types in assignment (expression has type "Type[str]", variable has type "Type[bytes]")
alembic/util/compat.py:75: error: Cannot assign multiple types to name "text_type" without an explicit "Type[...]" annotation
alembic/util/compat.py:75: error: Name 'unicode' is not defined
alembic/util/compat.py:84: error: Cannot assign to a type
alembic/util/compat.py:84: error: Name 'xrange' is not defined
alembic/util/compat.py:89: error: Name 'collections_abc' already defined (by an import)
alembic/util/compat.py:171: error: Name 'SafeConfigParser' already defined (possibly by an import)
alembic/util/compat.py:172: error: Name 'configparser' already defined (by an import)
alembic/util/compat.py:367: error: Name 'EncodedIO' already defined on line 329
alembic/util/langhelpers.py:20: error: Unsupported dynamic base class "with_metaclass"
alembic/util/langhelpers.py:29: error: Need type annotation for '_setups'
alembic/util/langhelpers.py:238: error: Incompatible types in assignment (expression has type "Callable[[immutabledict, VarArg(Any), KwArg(Any)], Any]", base class "dict" defined the type as "Callable[[Dict[Any, Any], Any], None]")
alembic/util/langhelpers.py:238: error: Incompatible types in assignment (expression has type "Callable[[immutabledict, VarArg(Any), KwArg(Any)], Any]", base class "dict" defined the type as "Callable[[Dict[Any, Any], Any, Any], None]")
alembic/util/langhelpers.py:238: error: Incompatible types in assignment (expression has type "Callable[[immutabledict, VarArg(Any), KwArg(Any)], Any]", base class "object" defined the type as "Callable[[object, str, Any], None]")
alembic/util/langhelpers.py:238: error: Incompatible types in assignment (expression has type "Callable[[immutabledict, VarArg(Any), KwArg(Any)], Any]", base class "dict" defined the type as "Callable[[Dict[Any, Any]], None]")
alembic/util/langhelpers.py:238: error: Incompatible types in assignment (expression has type "Callable[[immutabledict, VarArg(Any), KwArg(Any)], Any]", base class "MutableMapping" defined the type as overloaded function)
alembic/util/langhelpers.py:238: error: Incompatible types in assignment (expression has type "Callable[[immutabledict, VarArg(Any), KwArg(Any)], Any]", base class "dict" defined the type as "Callable[[Dict[Any, Any]], Tuple[Any, Any]]")
alembic/util/langhelpers.py:238: error: Incompatible types in assignment (expression has type "Callable[[immutabledict, VarArg(Any), KwArg(Any)], Any]", base class "dict" defined the type as "Callable[[Dict[Any, Any], Any, Any], Any]")
alembic/util/langhelpers.py:240: error: Incompatible types in assignment (expression has type "Callable[[immutabledict, VarArg(Any), KwArg(Any)], Any]", base class "dict" defined the type as overloaded function)
alembic/testing/assertions.py:62: error: Need type annotation for '_dialect_mods' (hint: "_dialect_mods: Dict[<type>, <type>] = ...")
alembic/ddl/impl.py:24: error: Need type annotation for '_impls' (hint: "_impls: Dict[<type>, <type>] = ...")
alembic/ddl/impl.py:29: error: Unsupported dynamic base class "with_metaclass"
alembic/ddl/oracle.py:24: error: Incompatible types in assignment (expression has type "Tuple[Set[str], Set[str], Set[str]]", base class "DefaultImpl" defined the type as "Tuple[Set[str]]")
alembic/ddl/mssql.py:29: error: Incompatible types in assignment (expression has type "Tuple[Set[str], Set[str]]", base class "DefaultImpl" defined the type as "Tuple[Set[str]]")
alembic/operations/ops.py:37: error: Need type annotation for '_mutations'
alembic/ddl/postgresql.py:41: error: Incompatible types in assignment (expression has type "Tuple[Set[str], Set[str]]", base class "DefaultImpl" defined the type as "Tuple[Set[str]]")
alembic/ddl/mysql.py:26: error: Incompatible types in assignment (expression has type "Tuple[Set[str], Set[str]]", base class "DefaultImpl" defined the type as "Tuple[Set[str]]")
alembic/ddl/mysql.py:27: error: Incompatible types in assignment (expression has type "List[str]", base class "DefaultImpl" defined the type as "Tuple[]")
alembic/script/revision.py:925: error: Need type annotation for 'nextrev'
alembic/script/revision.py:928: error: Need type annotation for '_all_nextrev'
alembic/testing/fixtures.py:43: error: Need type annotation for '_engs' (hint: "_engs: Dict[<type>, <type>] = ...")
tests/test_script_consumption.py:170: error: Incompatible types in assignment (expression has type "str", base class "ApplyVersionsFunctionalTest" defined the type as "bool")
tests/test_script_consumption.py:176: error: Incompatible types in assignment (expression has type "str", base class "ApplyVersionsFunctionalTest" defined the type as "bool")
tests/test_script_consumption.py:184: error: Incompatible types in assignment (expression has type "str", base class "ApplyVersionsFunctionalTest" defined the type as "bool")
tests/test_script_consumption.py:690: error: Incompatible types in assignment (expression has type "str", base class "IgnoreFilesTest" defined the type as "bool")
tests/test_script_consumption.py:694: error: Incompatible types in assignment (expression has type "str", base class "IgnoreFilesTest" defined the type as "bool")
tests/test_script_consumption.py:700: error: Incompatible types in assignment (expression has type "str", base class "IgnoreFilesTest" defined the type as "bool")
tests/_autogen_fixtures.py:212: error: Need type annotation for 'configure_opts' (hint: "configure_opts: Dict[<type>, <type>] = ...")
alembic/testing/plugin/plugin_base.py:25: error: Name 'ABC' already defined on line 22
tests/test_autogen_indexes.py:1203: error: Definition of "__requires__" in base class "NoUqReflection" is incompatible with definition in base class "AutogenerateUniqueIndexTest"
tests/test_autogen_diffs.py:587: error: Incompatible types in assignment (expression has type "str", base class "ModelOne" defined the type as "None")
tests/test_autogen_diffs.py:731: error: Need type annotation for 'configure_opts' (hint: "configure_opts: Dict[<type>, <type>] = ...")
tests/test_autogen_diffs.py:1190: error: Incompatible types in assignment (expression has type "str", base class "AutogenVersionTableTest" defined the type as "None")
tests/test_autogen_diffs.py:1203: error: Incompatible types in assignment (expression has type "str", base class "AutogenVersionTableTest" defined the type as "None")
tests/test_autogen_diffs.py:1384: error: Incompatible types in assignment (expression has type "str", base class "ModelOne" defined the type as "None")
tests/test_autogen_composition.py:250: error: Incompatible types in assignment (expression has type "str", base class "ModelOne" defined the type as "None")
Found 51 errors in 18 files (checked 85 source files)
```

**Comment by zzzeek** [comment]
I've been a little hesitant on pyi files.  what happens if we make a change in .py somehwere?  now it's out of sync, right?   not like we change alembic that often but this was why i was hoping to just wait on Python 3 and just do the annotations once, rather than 2 or 3 times (e.g. python 2 comments, etc)

**Comment by CaselIT** [comment]
I'm totally not up to date on this, but aren't there plugins for pytest to generate pyi files from the tests?

**Comment by zzzeek** [comment]
i tried one that dropbox makes and it was pretty rough to use.

**Comment by CaselIT** [comment]
is this one https://github.com/dropbox/pyannotate?

**Comment by zzzeek** [comment]
yeah that one.  it works but requires a ton of manual intervention

**Comment by CaselIT** [comment]
I've tried also https://github.com/google/pytype that seems to be actively developed (pyannotate seems not too active at the moment) but it's not really great either. 
Btw need to use `pytype -k alembic/ -x alembic/templates/   --no-report-errors` or it errors since we have multiple files with the same name...

**Comment by MartinThoma** [comment]
I've used monkeytype, but that also requires manual work

**Comment by CaselIT** [comment]
we added types in the source code. I think this could be closed. Thanks for starting the effort!

**Pull request closed without merging**
