### PR TITLE
Do not CAST(x as JSON) in SQLite

### PR DESCRIPTION
**Pull request by tiangolo**
### Description

When performing a batch operation for SQLite do not use `CAST(x as JSON)` when copying the data.

Instead, just copy the data as-is. SQLite already interprets it as JSON. But when using `CAST(x as JSON)` SQLite parses any JSON to a literal `0`.

This is probably just a bug in SQLite and/or the JSON extension for SQLite not being supported as a type in a `CAST()`. But as there are already other fixes/workarounds for compatibility in SQLAlchemy and Alembic, I thought this could be also included here.

I didn't see any code logic to specifically detect SQLite, but as the batch operations are only used in SQLite, and I saw [another commit](https://github.com/sqlalchemy/alembic/commit/3926ac6b000ed7f3dbdb5376a54f39351b3b4e35) to handle SQLite `CAST()` compatibility in the same section in the code, I thought it could be updated there as well. 

This would fix https://github.com/sqlalchemy/alembic/issues/697

Running the same script from that issue, after applying this, produces (my) expected results, here's the full log:

<details>

```
2020-05-22 19:56:11,678 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2020-05-22 19:56:11,678 INFO sqlalchemy.engine.base.Engine ()
2020-05-22 19:56:11,679 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2020-05-22 19:56:11,679 INFO sqlalchemy.engine.base.Engine ()
2020-05-22 19:56:11,680 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("users")
2020-05-22 19:56:11,680 INFO sqlalchemy.engine.base.Engine ()
2020-05-22 19:56:11,681 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("users")
2020-05-22 19:56:11,681 INFO sqlalchemy.engine.base.Engine ()
2020-05-22 19:56:11,681 INFO sqlalchemy.engine.base.Engine 
CREATE TABLE users (
        id INTEGER NOT NULL, 
        name VARCHAR, 
        data TEXT, 
        PRIMARY KEY (id)
)


2020-05-22 19:56:11,681 INFO sqlalchemy.engine.base.Engine ()
2020-05-22 19:56:11,681 INFO sqlalchemy.engine.base.Engine COMMIT
2020-05-22 19:56:11,682 INFO sqlalchemy.engine.base.Engine INSERT INTO users (name, data) VALUES (?, ?)
2020-05-22 19:56:11,682 INFO sqlalchemy.engine.base.Engine ('Jack', '{"message": "Hello World"}')
2020-05-22 19:56:11,682 INFO sqlalchemy.engine.base.Engine COMMIT
2020-05-22 19:56:11,682 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("users")
2020-05-22 19:56:11,682 INFO sqlalchemy.engine.base.Engine ()
2020-05-22 19:56:11,683 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'users' AND type = 'table'
2020-05-22 19:56:11,683 INFO sqlalchemy.engine.base.Engine ()
2020-05-22 19:56:11,683 INFO sqlalchemy.engine.base.Engine PRAGMA main.foreign_key_list("users")
2020-05-22 19:56:11,684 INFO sqlalchemy.engine.base.Engine ()
2020-05-22 19:56:11,684 INFO sqlalchemy.engine.base.Engine PRAGMA temp.foreign_key_list("users")
2020-05-22 19:56:11,684 INFO sqlalchemy.engine.base.Engine ()
2020-05-22 19:56:11,684 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'users' AND type = 'table'
2020-05-22 19:56:11,684 INFO sqlalchemy.engine.base.Engine ()
2020-05-22 19:56:11,685 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("users")
2020-05-22 19:56:11,685 INFO sqlalchemy.engine.base.Engine ()
2020-05-22 19:56:11,685 INFO sqlalchemy.engine.base.Engine PRAGMA temp.index_list("users")
2020-05-22 19:56:11,685 INFO sqlalchemy.engine.base.Engine ()
2020-05-22 19:56:11,685 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("users")
2020-05-22 19:56:11,685 INFO sqlalchemy.engine.base.Engine ()
2020-05-22 19:56:11,685 INFO sqlalchemy.engine.base.Engine PRAGMA temp.index_list("users")
2020-05-22 19:56:11,685 INFO sqlalchemy.engine.base.Engine ()
2020-05-22 19:56:11,686 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'users' AND type = 'table'
2020-05-22 19:56:11,686 INFO sqlalchemy.engine.base.Engine ()
2020-05-22 19:56:11,687 INFO sqlalchemy.engine.base.Engine 
CREATE TABLE _alembic_tmp_users (
        id INTEGER NOT NULL, 
        name VARCHAR, 
        data JSON, 
        PRIMARY KEY (id)
)


2020-05-22 19:56:11,687 INFO sqlalchemy.engine.base.Engine ()
2020-05-22 19:56:11,687 INFO sqlalchemy.engine.base.Engine COMMIT
2020-05-22 19:56:11,688 INFO sqlalchemy.engine.base.Engine INSERT INTO _alembic_tmp_users (id, name, data) SELECT users.id, users.name, users.data 
FROM users
2020-05-22 19:56:11,688 INFO sqlalchemy.engine.base.Engine ()
2020-05-22 19:56:11,688 INFO sqlalchemy.engine.base.Engine COMMIT
2020-05-22 19:56:11,688 INFO sqlalchemy.engine.base.Engine 
DROP TABLE users
2020-05-22 19:56:11,688 INFO sqlalchemy.engine.base.Engine ()
2020-05-22 19:56:11,688 INFO sqlalchemy.engine.base.Engine COMMIT
2020-05-22 19:56:11,688 INFO sqlalchemy.engine.base.Engine ALTER TABLE _alembic_tmp_users RENAME TO users
2020-05-22 19:56:11,688 INFO sqlalchemy.engine.base.Engine ()
2020-05-22 19:56:11,689 INFO sqlalchemy.engine.base.Engine COMMIT
2020-05-22 19:56:11,689 INFO sqlalchemy.engine.base.Engine SELECT users.id, users.name, users.data 
FROM users
2020-05-22 19:56:11,689 INFO sqlalchemy.engine.base.Engine ()
Jack, {"message": "Hello World"}
```

</details>

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by zzzeek** [comment]
hi there and thanks for this PR.

haven't looked deeply yet but we unfortunately cannot hardcode databse-specific, type-specific rules inside of batch.py like that.    the problem needs to be solved in a different way that takes into account what the actual problem is in a generic way.

**Comment by tiangolo** [comment]
Awesome, thanks a lot for taking a look into this and for the guidance. I updated the PR with your patch and these changes on top.

**Comment by zzzeek** [comment]
okey doke I'll pull it into gerrit

**Comment by sqla-tester** [comment]
New Gerrit review created for change c9ef28e69cb29fc9811476dda3a329fe16aa4675: https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2011

**Comment by zzzeek** [comment]
the test needs some requirements decorators to make sure it only runs on sqlalhcemy 1.3 or higher since there's no sqlite json in 1.2 or earlier

**Comment by tiangolo** [comment]
Great!

I added the decorator (I hope correctly) based on what I saw in other tests. But I'm not really sure how to test the decorator locally, I hope that's correct.

**Comment by sqla-tester** [comment]
Patchset 6618325258bd90ec257b09c17d44421a5642b1b1 added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2011

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+2

looks great thanks very much!

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2011

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2011 has been **merged**. Congratulations! :)

**Comment by tiangolo** [comment]
Awesome! Thanks! :rocket:

**Pull request closed without merging**
