### PR TITLE
Fix typo in alembic.ini templates

### PR DESCRIPTION
**Pull request by merwan**
### Description

Fix typo in alembic.ini templates: requied => required

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision e200e174da7d6ca4ae943fc48cd7ff9af686f11a of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change e200e174da7d6ca4ae943fc48cd7ff9af686f11a: https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4978

**Comment by zzzeek** [comment]
thanks!

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4978 has been **merged**. Congratulations! :)

**Pull request closed without merging**
