### PR TITLE
Fix constraint_name type of create_foreign_key

### PR DESCRIPTION
**Pull request by TilmanK**
Make the type of contraint_name optional in create_foreign_key

### Description
- Make the type of `contraint_name` optional in `create_foreign_key` as stated in the documentation (passing `None` will auto-generate a constraint name).
- Fixes some typos/inconsistencies in documentation.

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by CaselIT** [comment]
Hi,

The pyi files are auto-generated as mentioned at the top of the file, so you should update the typing and documentation in the `alembic/operations/ops.py` then re-run the genetion script in `tools/`

**Comment by TilmanK** [comment]
Hey @CaselIT,

sorry, I haven't read that particular line and didn't notice that the source files are actually typed. Are you going to squash the three commits, or shall I rework them into one?

**Comment by CaselIT** [comment]
> Are you going to squash the three commits, or shall I rework them into one?

they will be squased by gerrit, so it's fine to have multiple commits.

I'll make the test run

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision d985abb8ec7ee24f234a9d73721f5b189d47dc92 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change d985abb8ec7ee24f234a9d73721f5b189d47dc92: https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3075

**Comment by CaselIT** [comment]
Since we are changing this, also create_primary_key accepts `None` as name

**Comment by TilmanK** [comment]
What about `create_index`?

**Comment by CaselIT** [comment]
I guess all of the create_xx that mention that it can be None

**Review by sqla-tester — COMMENTED** [review]
**mike bayer** (zzzeek) wrote:

i say fix that pk one , then merge

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3075

* alembic/op.pyi (line 621): yes

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 39d44af226b2103da3964daf3229880a0958b97c of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 39d44af226b2103da3964daf3229880a0958b97c added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3075

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

i was merging this and missed it!!  1.7.3 is right now sorry

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3075

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3075 has been **merged**. Congratulations! :)

**Pull request closed without merging**
