### PR TITLE
Update of the no-empty-migrations snippet to work with alembic check

### PR DESCRIPTION
**Pull request by BayerSe**
### Description
Update of the no-empty-migrations snippet to work with alembic check, see https://github.com/sqlalchemy/alembic/discussions/1332

### Checklist

This pull request is:

- [ x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by sqla-tester** [comment]
New Gerrit review created for change eeb7cdab9559b0500be8f1543fad97f5305f2b0f: https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4915

**Comment by CaselIT** [comment]
thanks!

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

thanks!

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4915

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4915 has been **merged**. Congratulations! :)

**Pull request closed without merging**
