### PR TITLE
Update license year to 2024

### PR DESCRIPTION
**Pull request by evilaliv3**

### CODE REVIEW

**Comment by CaselIT** [comment]
thanks!

@zzzeek since sqlalchemy has now gained a script to manage the file headers and the dates should be copy it also to alembic? Or too much effort?

**Comment by zzzeek** [comment]
> thanks!
> 
> @zzzeek since sqlalchemy has now gained a script to manage the file headers and the dates should we copy it also to alembic? Or too much effort?

probably.  Typically I run a script here anyway, but it's not sustainable that we wait for PRs like this

**Comment by CaselIT** [comment]
I don't think updating the year is actually needed for the license to be value, but I'm not a layer so 🤷‍♂️

Let's accept this PR and maybe think if the script for the year makes sense also here

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 477619ca80e04484ac5bf46c03e7c39df3ecd2bc of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 477619ca80e04484ac5bf46c03e7c39df3ecd2bc: https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/5116

**Comment by sqla-tester** [comment]
**Michael Bayer** (zzzeek) wrote:

thank you!

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/5116

**Pull request closed without merging**
