### PR TITLE
Fix mypy linting issues

### PR DESCRIPTION
**Pull request by maver1ck**
### Description

Fixing mypy linting issues for new mypy version.

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision a79d47d3acf7ae628ead7ca829bfe1c6f864c3c9 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change a79d47d3acf7ae628ead7ca829bfe1c6f864c3c9: https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/5559

**Comment by CaselIT** [comment]
thanks!

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/5559 has been **merged**. Congratulations! :)

**Pull request closed without merging**
