### PR TITLE
Implement downgrade of a single branch back to a branchpoint.  Fixes: #464

### PR DESCRIPTION
**Pull request by simonbowly**
### Description

Current downgrade behaviour downgrades all branches when asked to downgrade to a branchpoint.  This PR implements syntax suggested in #464 to downgrade single branches.

Basic example:
```
base -> rev1 --> rev2 (brancha)
             +-> rev2a (branchb) -> rev3a
```

a) The following will only downgrade `rev2 -> rev1`, leaving `rev3a` as the single current head:
- `alembic downgrade rev2@rev1`
- `alembic downgrade brancha@rev1`

b) The following will only downgrade `rev3a -> rev2a` and `rev2a -> rev1`, leaving `rev2` as the single current head:
- `alembic downgrade rev3a@rev1`
- `alembic downgrade rev2a@rev1`
- `alembic downgrade branchb@rev1`

Note:

If `rev3a` or `rev2a` depend on `rev2`:

- Case (b) is unchanged
- Case (a) downgrades both branches.  It's only strictly necessary to remove `rev3a` if `rev2a` does not have a dependency, but considering entire branches is simpler to implement and `rev3a` alone can already be removed using `downgrade rev2a`.

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [x] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

### CODE REVIEW

**Comment by zzzeek** [comment]
impressive, I have no idea how that part of the code works anymore :)

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 997ec36ec2f2f1187cd632542456fa1cf7919313 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 997ec36ec2f2f1187cd632542456fa1cf7919313: https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2387

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Workflow+1

great job.  I'd like to take some time to work through how this works but I plan to have this be part of alembic 1.5, which is also dependent on some sqlalchemy stuff I need to get finished.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2387

**Comment by sqla-tester** [comment]
**Simon Bowly** (simonbowly) wrote:

> Patch Set 1: Workflow+1
> 
> great job.  I'd like to take some time to work through how this works but I plan to have this be part of alembic 1.5, which is also dependent on some sqlalchemy stuff I need to get finished.

Cheers! Hopefully the patch only affects this specific syntax - but I'm not sure I'm across all the use cases. Let me know if changes or docs are needed.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2387

**Review by sqla-tester — COMMENTED** [review]
**mike bayer** (zzzeek) wrote:

Code-Review-1

(1 comment)

took a look and I think given the inconsistencies we see in https://github.com/sqlalchemy/alembic/issues/765 , we are looking at a behavioral change, which is fine, but if we are going to do it, we should get it right.   i think 765 should be addressed in the same issue here because it is highly related to how we interpret these revision identifiers.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2387

* tests/test_version_traversal.py (line 316): this test, as we are talking about in https://github.com/sqlalchemy/alembic/issues/765, has to change also, right?   it should only act on d2 and c2, and the "heads" should end up being "b, d1".

but *then*, if they try to downgrade "c2branch@<a revision>", it should *raise*.  because you can't downgrade only c2branch and arrive at "a", because it suggests undoing "b" for which c1 is dependent upon.

I know that using the branch identifier in this way is my idea, but I think this makes more sense and it *is* a behavioral change.  like if someone refers to a branch name, of course they want to work only on that branch, right?    they should not be allowed to traverse outside of that branch such that other branches are affected.  and relative identifiers should work too.

**Comment by sqla-tester** [comment]
**Simon Bowly** (simonbowly) wrote:

Understood. And yes you're right, c2branch@base+2 should probably be equivalent to c2branch@b, which this issue says should only drop one branch.

I'll have a go at rolling all this up into one PR and documenting these cases.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2387

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

I think this is superseded by https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2530 

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2387

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2387 has been **abandoned**.  That means that at least for the moment I need to close this pull request. Sorry it didn't work out :(

**Comment by sqla-tester** [comment]
**Simon Bowly** (simonbowly) wrote:

Yes, 2530 changeset covers this. Busy times at work at the moment so I have not had a chance to finish the required changes for --sql mode. Should be onto it in a couple of weeks.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2387

**Comment by zzzeek** [comment]
no worries at all I'm pushing out 8-10 regression fixes per day for sqlalchemy 1.4, im booked   ....

**Pull request closed without merging**
