### PR TITLE
set default None for user_module_prefix

### PR DESCRIPTION
**Pull request by allmonday**
fix https://github.com/sqlalchemy/alembic/issues/1235
fix KeyError of `prefix = autogen_context.opts["user_module_prefix"]` in render.py

### Description
I've made a small snippet to generate create_table ops for my models
```python
def create_orm_migration(metadata):

    operations = []
    for table in metadata.tables.values():
        if table.name.startswith('meeting_note'):
            operations.append(
                ops.CreateTableOp.from_table(table)
            )
            for idx in table.indexes:
                operations.append(ops.CreateIndexOp.from_index(idx))

    print(autogenerate.render_python_code(
        ops.UpgradeOps(ops=operations),
        ), 
    )


```
and it raises KeyError because UUID is defined in other modules.
```python
from portal.utils.db import UUID

Base = declarative_base()

class MeetingNotes(Base, CommonFieldsMixin):
    __tablename__ = 'meeting_note_notes'

    id = Column(UUID, primary_key=True, default=uuid.uuid1)
    date = Column(Date)
    duration = Column(Integer)
    category = Column(String(1024))
    type = Column(String())
    host_employee_number = Column(Integer)
    content = Column(Text(100000))
    title = Column(String(1024))
    agenda = Column(Text())
```
this happens in `autogenerate.render:_user_autogenerate_prefix`, first I attempt to change 

```python
prefix = autogen_context.opts["user_module_prefix"]
# to
prefix = autogen_context.opts.get("user_module_prefix")
```

after I review code around, I guess this is designed to use `[]` instead of `.get()`, so I follow the code style and add the default argument `user_module_prefix` into `autogenerate.api:render_python_code`

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by CaselIT** [comment]
Hi,

Thanks for the PR. Can you also open an issue so we can properly create a changelog?

Thanks!

**Comment by allmonday** [comment]
Hi，
linked with https://github.com/sqlalchemy/alembic/issues/1235 ~

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 6fa3bc1ce4f2130bf7a28282a84e3bb9a3223304 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4609 has been **merged**. Congratulations! :)

**Pull request closed without merging**
