### PR TITLE
Fixes: #1348 Typings for target_metadata sequence of metadatas

### PR DESCRIPTION
**Pull request by iurisilvio**
Ref #1348 

Add `Sequence[MetaData]` typing to `target_metadata` args.

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by iurisilvio** [comment]
I tried to write a test for the typing, but mypy don't look into tests folder. I think alembic needs a test for the feature of metadata sequences, but I don't know how/where to write it.

**Comment by zzzeek** [comment]
alembic doesnt have typing tests right  now

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 5fcdaf5a6075303b8fb14646f3b93e4c2f76a772 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 5fcdaf5a6075303b8fb14646f3b93e4c2f76a772: https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4965

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

ok it's good, thanks!

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4965

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4965 has been **merged**. Congratulations! :)

**Pull request closed without merging**
