### PR TITLE
standardizing to other SqlAlchemy coding conventions:

### PR DESCRIPTION
**Pull request by jvanasco**
* migrated `black` config to `pyproject.toml`
* updated black version
* updated README to showcase code-of-conduct and development links

This addresses the repo-wide handling of this situation

### CODE REVIEW

**Comment by sqla-tester** [comment]
New Gerrit review created for change a3584c5d7e21d4d64c989981a80f28d404579542: https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/1771

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

OK this is not working for some reason:

[classic@photon3 alembic]$ black alembic/util/compat.py
All done! ✨ 🍰 ✨
1 file left unchanged.
[classic@photon3 alembic]$ flake8 alembic/util/compat.py 
alembic/util/compat.py:280:13: E211 whitespace before '('
alembic/util/compat.py:312:9: E211 whitespace before '('

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/1771

**Comment by jvanasco** [comment]
Is there an easy way in gerrit to determine what the patch-set you uploaded is?

It looks like the first patch-set added some commas and removed spaces - which raises some concerns to me about the right black version being picked up.

it looks like the second patch set was just the changelog..

i had to manually compare versions to figure this out, as I can't find this functionality in gerrit.

**Comment by zzzeek** [comment]
I took out the py27 directive.  so there are two patch sets, one is from this PR and the other is the change I made:

https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/1771/1
https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/1771/2


depending on which UX you have set (the more modern looking polygerrit one seems to be the default) there's a little dropdown of "Patchset" sort of in the middle-left that has the different versions.

**Comment by zzzeek** [comment]
OK this is being done in gerrit now, @CaselIT  did the black stuff in a separate review, this will be just the README.  thanks!

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/1771

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Verified+1

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/1771

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/1771 has been **merged**. Congratulations! :)

**Comment by CaselIT** [comment]
ops sorry, I did not notice this open on gerrit

**Pull request closed without merging**
