### PR TITLE
Annotate batch_alter_table

### LINKED ISSUE #975: Add BatchOperations return type annotation to batch_alter_table
https://github.com/sqlalchemy/alembic/blob/5fce5dbd53cd23c972e82f8cba91a3b4624e523b/alembic/operations/base.py#L210-L222

### PR DESCRIPTION
**Pull request by bodevone**
### Description
Closes #975 

### Checklist

This pull request is:

- [X] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by CaselIT** [comment]
thanks for the pr!

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision a111d4f446e861bd01a3cea7ebd1c18a2446601a of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change a111d4f446e861bd01a3cea7ebd1c18a2446601a: https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3894

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3894 has been **merged**. Congratulations! :)

**Pull request closed without merging**
