### PR TITLE
add a test to verify that case insensitive table names dont generate …

### PR DESCRIPTION
**Pull request by pbecotte**
…spurious autogen. Wrote this to check #628 - no code changes were necessary, so probably not worth actually merging this, but figured I'd offer the PR anyway :)

### CODE REVIEW

**Comment by sqla-tester** [comment]
New Gerrit review created for change 97803b34788d61a63b459226b7229d40cb8326a7: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/alembic/+/1592

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

sorry, the alembic tests are pretty crude as my testing-fu was not at master levels when i wrote these tests :)

**Comment by pbecotte** [comment]
Interesting, in Jenkins the tests showed exactly the behavior I was trying to prove didn't happen haha. Problem is, I ran them against Oracle before submitting the PR. I need to up my Oracle-Fu ... take 6 minutes for the damn thing to start up, and it periodically gets into a state that every query takes 5 seconds and I have to delete it and start over.

**Comment by zzzeek** [comment]
Im not sure things will work in Oracle (and Firebird ) if you are setting up case-sensitive UPPERCASE names on both sides.   nobody actually does this in practice, so that's good.

**Comment by zzzeek** [comment]
right so...if we ask Oracle for the table "sometable", it is stored in the oracle catalog tables as SOMETABLE, so we ask, and we get back...."SOMETABLE".     If we are given case sensitive "SOMETABLE", again we ask Oracle for "SOMETABLE" and we get back..."SOMETABLE".   So there's no way for SQLAlchemy to know, when it gets back a plain list of table names, when it sees "SOMETABLE" to know if that is case sensitive "SOMETABLE" or case insensitive SOMETABLE, unless we can locate some new field in Oracle that tells us this.    this would have to be some fairly intricate change on the SQLAlchemy side that would impact how reflection works at a core level.

**Comment by zzzeek** [comment]
annnndddd...this is becasue there is no "case sensitivity" in how the name is stored:

```
from sqlalchemy import create_engine

e = create_engine(
    "oracle://scott:tiger@oracle1120",
    echo='debug'
)
with e.connect() as conn:
    conn.execute('CREATE TABLE "FOO" (id integer primary key)' )

    # works, case insensitive name matches
    conn.execute("SELECT * from foo")

    # fails, because "foo" already exists
    conn.execute('CREATE TABLE foo (id integer primary key)' )

```

meaning, you cannot have a table name called "ALL_UPPERCASE" on Oracle and have it match in a case-sensitive fashion.  the test makes no sense for Oracle.

**Comment by zzzeek** [comment]
by "match" i mean, reflect it back, unless there were some special client side flag we were using to make it do that when we do get_table_names(), it gets a little crazy.   just use all lower case names :)

**Comment by zzzeek** [comment]
it works like this though...not sure if we have a test like this but I would think there's one in there
```

        Table(
            'MyTable',
            m,
            Column('Ident', Integer, Sequence('Id_Seq'), primary_key=True),
        )

```

those names are unambiguously case sensitive

**Comment by pbecotte** [comment]
Sounds good- I think I misunderstood some of the code. Glad for the learning experience though :)

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

closed upstream

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1592 has been **abandoned**.  That means that at least for the moment I need to close this pull request. Sorry it didn't work out :(

**Pull request closed without merging**
