### PR TITLE
Add missing whitespace to configuration template and doc example.

### PR DESCRIPTION
**Pull request by arusahni**
As a developer who uses whitespace-sensitive programming language, this made my eye twitch 😄

### CODE REVIEW

**Comment by zzzeek** [comment]
oh wow, indeed :)

**Comment by zzzeek** [comment]
sorry my script seems to have failed, moment

**Comment by sqla-tester** [comment]
New Gerrit review created for change 5315a92ff2d88699ea0404c2ebb56fc3833452ed: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/alembic/+/1168

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

thanks for the contribution!

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1168 has been **merged**. Congratulations! :)

**Pull request closed without merging**
