### PR TITLE
Fix postgresql_include in create_index

### LINKED ISSUE #874: KeyError on postgresql_include
Like #513, but for PostgreSQL.  Porting e01041b worked for me.

### PR DESCRIPTION
**Pull request by sbronson**
### Description
Fix #874.  Copied from e01041b and 174cb4b.

### Checklist
This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision e819580c3d904e5fbfe8dc963c9eb77858101085 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Failed to create a gerrit review, git squash against branch 'master' failed

**Comment by zzzeek** [comment]
this needs to be rebased

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 2f9b51890a1296146bcea842dc8bbee53d1d11f5 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 2f9b51890a1296146bcea842dc8bbee53d1d11f5: https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3010

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3010 has been **merged**. Congratulations! :)

**Pull request closed without merging**
