### PR TITLE
Fixes #716. Remove typo in _exec_drop_col_fk_constraint

### LINKED ISSUE #716: mssql_drop_foreign_key generates statement that raises pyodbc.ProgrammingError (Incorrect syntax near '`')
**Describe the bug**
```py
op.drop_column("assignment", "employee_profile_id", mssql_drop_foreign_key=True)
```
This line is [generating the following statement](https://github.com/sqlalchemy/alembic/blob/52ef05c936170109f2f457751f4940e4269595c3/alembic/ddl/mssql.py#L200):
```sql
declare @const_name varchar(256)
select @const_name = [name] from
sys.foreign_keys fk join sys.foreign_key_columns fkc
on fk.object_id=fkc.constraint_object_id
where fkc.parent_object_id = object_id('assignment')
`and col_name(fkc.parent_object_id, fkc.parent_column_id) = 'employee_profile_id'
exec('alter table assignment drop constraint ' + @const_name)
```
which leads to pyodbc.ProgrammingError:
```
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '`'. (102) (SQLExecDirectW)")
```
**Expected behavior**
Foreign key dropped alongside column without errors.

**Versions.**
 - OS: Ubuntu 18.04
 - Python: 3.7.4
 - Alembic: 1.4.2
 - SQLAlchemy: 1.3.14
 - Database: Azure SQL Server
 - DBAPI: pyodbc==4.0.30

### PR DESCRIPTION
**Pull request by Nuqlear**
### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

### CODE REVIEW

**Comment by CaselIT** [comment]
Thanks for the fix, I'll make it run on the ci

**Comment by sqla-tester** [comment]
New Gerrit review created for change dcd90fb4dfe8acd63670aedbdee58be25d4781d2: https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2105

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

Code-Review+1 Workflow+2

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2105

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+2

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2105

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2105 has been **merged**. Congratulations! :)

**Pull request closed without merging**
