### PR TITLE
Fixed CLI output when running post_write hooks

### LINKED ISSUE #1261: Badly formatted output when running post-write hooks
**Describe the bug**
There is a small output bug when running `alembic revision ...` with a post-write hook. The name of the hook is not correctly displayed:

```bash
$ alembic revision -m 'my new revision'        
  Generating myrepo/migrations/versions/202306151538_my_new_revision.py_ ...  done
  Running post write hook {name!r} ... # Display bug HERE
reformatted myrepo/migrations/versions/202306151538_my_new_revision.py

All done! ✨ 🍰 ✨
1 file reformatted.
  done
```

Happy to fix, if approved!

**Expected behavior**
This output
```bash
$ alembic revision -m 'my new revision'        
  Generating myrepo/migrations/versions/202306151538_my_new_revision.py_ ...  done
  Running post write hook black ... # Display bug HERE
reformatted myrepo/migrations/versions/202306151538_my_new_revision.py

All done! ✨ 🍰 ✨
1 file reformatted.
  done
```
when `black` hook is configured.

**To Reproduce**
```bash
$ mkdir testdir
$ cd testdir
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install alembic
```

Uncomment default `post_write_hooks` parameters in `alembic.ini`
```ini
[post_write_hooks]
black.type = console_scripts
black.entrypoint = black
black.options = -l 79 REVISION_SCRIPT_FILENAME
```

Then run revision command
```bash
alembic revision -m 'my new revision'
```

**Error**

```bash
# Command output
  Generating workspace/testdir/migrations/versions/324b3e655f54_my_new_revision.py ...  done
  Running post write hook {name!r} ...
...
```

**Versions.**
 - OS: macOS
 - Python: 3.11
 - Alembic: 1.11.1
 - SQLAlchemy: 2.0.16
 - Database: PostgreSQL 15.3
 - DBAPI: N/A

**Additional context**
Bug seems to be here: https://github.com/sqlalchemy/alembic/blob/79738c9e971d4bbe6f4845a54fd0f972d15e1035/alembic/script/write_hooks.py#L88

**Have a nice day!**

### PR DESCRIPTION
**Pull request by duc00**
Fixes: #1261 

### Description
Just fixed badly written Python string interpolation. Used the `%` operator just like the lines above.

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by CaselIT** [comment]
Thanks. Maybe we could use f-strints tough?

**Comment by duc00** [comment]
> Thanks. Maybe we could use f-strints tough?

Sure. I was worried about compatibility with lower Python versions but found out Alembic support 3.7+. No worries then.

Shall I update all occurrences in the file? Don't know what the policy is concerning updating outdated code.

**Comment by CaselIT** [comment]
> 
> Shall I update all occurrences in the file? Don't know what the policy is concerning updating outdated code.

As you prefer

**Comment by duc00** [comment]
Done. Let me know

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 19d17f5d061319bbf142b45a593081da5fc1dda8 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 19d17f5d061319bbf142b45a593081da5fc1dda8: https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4731

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

hi and thanks for this!

as trivial as this is, it fixes a user-facing bug so likely needs a changelog.   otherwise peopel dont know what they are getting when they download a newer version

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4731

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4731 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

updated the change log. Sadly I did commit & push and it merged it..

git review -d id sets the upstream to main 😞

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4731

**Pull request closed without merging**
