### PR TITLE
render table name with schema

### PR DESCRIPTION
**Pull request by matthew-emw**
currently, updating comments on tables doesn't explicitly reference schema, and doesn't quote table names appropriately

### CODE REVIEW

**Comment by zzzeek** [comment]
hi there -

for bugs, please file an issue at https://github.com/sqlalchemy/alembic/issues first.   Tests need to be added here for the quoting issue as well.

**Comment by zzzeek** [comment]
also please include `Fixes: #<issuenum>` in the commit message.  thanks!

**Comment by matthew-emw** [comment]
@zzzeek thanks for your comments - hopefully all addressed.

**Comment by sqla-tester** [comment]
New Gerrit review created for change b98fb37d0c2c53fda773f188adca96cc8bfd1005: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/alembic/+/1619

**Comment by zzzeek** [comment]
I use [pre-commit](https://pre-commit.com/) with black to produce a deterministic code formatting, if you install the hook it will also do flake8 before it gets pushed.

**Comment by zzzeek** [comment]
oh the flake8 hook is not in the alembic/.pre-commit-config.yaml yet, but it will run black.

**Comment by zzzeek** [comment]
nice!  the thing about black is, even if you format your code perfectly and pass pep8, when later on black gets run on the source file it will still change it and produce a diff.   I haven't figured out a way around this particular problem.

**Comment by sqla-tester** [comment]
Patchset 703e27bab5b2d0907367dd03a4babb00ea5ee8aa added to existing Gerrit review https://gerrit.sqlalchemy.org/#/c/sqlalchemy/alembic/+/1619

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1619 has been **merged**. Congratulations! :)

**Comment by zzzeek** [comment]
thanks for your help on this!

**Pull request closed without merging**
